server:
  port: 9000
  servlet:
    context-path: /community
    encoding:
      enabled: true
      charset: utf-8
      force: true


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: admin
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000

  thymeleaf:
    cache: false

  mail:
    host: smtp.qq.com
    port: 465
    username: wimp.wangt@qq.com
    password: ksbkhazpdmlfceeh
    protocol: smtps
    properties:
      mail.smtp.ssl.enable: true

  redis:
    host: localhost
    port: 4396
    password: 'Cloud1944:'

  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000


mybatis:
  mapper-locations:
    - classpath:mappers/*.xml
  type-aliases-package: com.kwimps.community.entity
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #启用自动生成主键
    use-generated-keys: true
    #匹配驼峰命名和下划线命名
    map-underscore-to-camel-case: true

#community
community:
  path:
    domain: "http://101.37.36.161:9000"
    upload: "/home/kwimp/community/upload/header"


logging:
  config: "classpath:logback-prod.xml"

